spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/CART
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

server:
  port: 8084

security:
  enabled: true
  user-url: http://user-service/api/auth/{email}
  jwt-expiration: 864000000
  jwt-secret: secretKeyToProviderJWT
  refresh-token-url: http://user-service/api/auth/refresh-token/{refresh_token}
  refresh-expiration: 3600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



