spring:
  application:
    name: discovery
server:
  port: 8769
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka